# Generated by Django 4.1.9 on 2023-06-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobsource_finale_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsource',
            name='link',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
