exclude: "^docs/|/migrations/"
default_stages: [commit]

repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.230"
    hooks:
      - id: ruff

  - repo: https://github.com/fpgmaas/deptry.git
    rev: "0.8.0"
    hooks:
      - id: deptry
        # args: ["--skip-missing"]


# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
